services:
  echo-server:
    build: ./
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 50m
    env_file:
      - stack.env
    ports:
      - '${PORT}:7000'

networks:
  default:
    external:
      name: proxy